// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

library flutter_candies_demo_library_route;

export 'src/widget/pic_swiper.dart';
